using MixedRealityExtension.App;
using MixedRealityExtension.Core.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MixedRealityExtension.PluginInterfaces
{
	/// <summary>
	/// Service to provide IUserInfo for userId.
	/// </summary>
	public interface IUserInfoProvider
	{
		/// <summary>
		/// Get an IUserInfo for the given user.
		/// </summary>
		/// <param name="app">The mixed reality extension app making the call.</param>
		/// <param name="userId">The obfuscated id of the user (generated by the platform).</param>
		/// <returns>The IUserInfo instance, or null if user not found.</returns>
		IUserInfo GetUserInfo(IMixedRealityExtensionApp app, Guid userId);
	}

	internal class NullUserInfoProvider : IUserInfoProvider
	{
		public IUserInfo GetUserInfo(IMixedRealityExtensionApp app, Guid userId)
		{
			return null;
		}
	}
}
